/*
 * Based on the UCB version of strftime.c with the copyright notice appearing below.
 */

/*
** Copyright (c) 1989 The Regents of the University of California.
** All rights reserved.
**
** Redistribution and use in source and binary forms are permitted
** provided that the above copyright notice and this paragraph are
** duplicated in all such forms and that any documentation,
** advertising materials, and other materials related to such
** distribution and use acknowledge that the software was developed
** by the University of California, Berkeley. The name of the
** University may not be used to endorse or promote products derived
** from this software without specific prior written permission.
** THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
** IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*/
package android.text.format;

import android.content.res.Resources;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.Formatter;
import java.util.Locale;
import java.util.TimeZone;
import libcore.icu.LocaleData;
import libcore.util.ZoneInfo;

import static libcore.io.IoUtils.closeQuietly;

/**
 * Formatting logic for {@link Time}. Contains a port of Bionic's broken strftime_tz to Java.
 *
 * <p>There is some non-obvious complexity in this implementation.
 *
 * <p>Complexity because of the original native code which...
 * <ul>
 *     <li>Mostly operated on individual bytes and (incorrectly) assumed ASCII.</li>
 *     <li>Used UTF-8 to convert to and from Java Strings. i.e. for the pattern strings and the
 *     generated bytes even though most of the code assumes ASCII.</li>
 * </ul>
 *
 * <p>Complexity because of Java which...
 * <ul>
 *     <li>Has a signed byte type and an unsigned char type. Converting from byte to char requires
 *     the use of "& 0xFF" ({@link #convertToChar(byte)}</li>
 *     <li>Converts bytes and chars to ints for most operators (comparison, arithmetic).</li>
 * </ul>
 *
 * <p>The following implementation strategy has been adopted:
 * <ul>
 *     <li>We mimic the original native behavior as much as possible. i.e. first generate a
 *     set of bytes, do horrible things and then convert to Java characters at the end.</li>
 *     <li>Avoid mixing byte with char on an operation: convert the byte to a char or both to int
 *     where possible unless it is obviously safe not to do so.
 *     </li>
 * </ul>
 *
 * <p>This class is not thread safe.
 */
class TimeFormatter {
    // An arbitrary value outside the range representable by a byte / ASCII character code.
    private static final int FORCE_LOWER_CASE = 0x100;

    private static final int SECSPERMIN = 60;
    private static final int MINSPERHOUR = 60;
    private static final int DAYSPERWEEK = 7;
    private static final int MONSPERYEAR = 12;
    private static final int HOURSPERDAY = 24;
    private static final int DAYSPERLYEAR = 366;
    private static final int DAYSPERNYEAR = 365;

    /**
     * The Locale for which the cached LocaleData and formats have been loaded.
     */
    private static Locale sLocale;
    private static LocaleData sLocaleData;
    private static String sTimeOnlyFormat;
    private static String sDateOnlyFormat;
    private static String sDateTimeFormat;

    private final LocaleData localeData;
    private final String dateTimeFormat;
    private final String timeOnlyFormat;
    private final String dateOnlyFormat;
    private final Locale locale;

    private OutputStream emittedBytesStream;
    private Formatter formatter;

    public TimeFormatter() {
        synchronized (TimeFormatter.class) {
            Locale locale = Locale.getDefault();

            if (sLocale == null || !(locale.equals(sLocale))) {
                sLocale = locale;
                sLocaleData = LocaleData.get(locale);

                Resources r = Resources.getSystem();
                sTimeOnlyFormat = r.getString(com.android.internal.R.string.time_of_day);
                sDateOnlyFormat = r.getString(com.android.internal.R.string.month_day_year);
                sDateTimeFormat = r.getString(com.android.internal.R.string.date_and_time);
            }

            this.dateTimeFormat = sDateTimeFormat;
            this.timeOnlyFormat = sTimeOnlyFormat;
            this.dateOnlyFormat = sDateOnlyFormat;
            this.locale = locale;
            localeData = sLocaleData;
        }
    }

    /**
     * Format the specified {@code wallTime} using {@code pattern}. The output is returned.
     */
    public String format(String pattern, ZoneInfo.WallTime wallTime, ZoneInfo zoneInfo) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        OutputStreamWriter osw = new OutputStreamWriter(baos, StandardCharsets.UTF_8);
        try {
            this.emittedBytesStream = baos;
            formatter = new Formatter(osw, locale);

            formatInternal(pattern, wallTime, zoneInfo);
            String result = new String(baos.toByteArray(), StandardCharsets.UTF_8);
            // This behavior is the source of a bug since some formats are defined as being
            // in ASCII. Generally localization is very broken.
            if (localeData.zeroDigit != '0') {
                result = localizeDigits(result);
            }
            return result;
        } finally {
            closeQuietly(osw);
            this.emittedBytesStream = null;
            formatter = null;
        }
    }

    private String localizeDigits(String s) {
        int length = s.length();
        int offsetToLocalizedDigits = localeData.zeroDigit - '0';
        StringBuilder result = new StringBuilder(length);
        for (int i = 0; i < length; ++i) {
            char ch = s.charAt(i);
            if (ch >= '0' && ch <= '9') {
                ch += offsetToLocalizedDigits;
            }
            result.append(ch);
        }
        return result.toString();
    }

    /**
     * Format the specified {@code wallTime} using {@code pattern}. The output is written to
     * {@link #emittedBytesStream}.
     */
    private void formatInternal(String pattern, ZoneInfo.WallTime wallTime, ZoneInfo zoneInfo) {
        // Convert the pattern to bytes to be compatible with old native implementation behavior.
        byte[] bytes = pattern.getBytes(StandardCharsets.UTF_8);
        if (bytes.length == 0) {
            return;
        }

        ByteBuffer formatBuffer = ByteBuffer.wrap(bytes);
        while (formatBuffer.remaining() > 0) {
            boolean outputCurrentByte = true;
            byte currentByte = formatBuffer.get(formatBuffer.position());
            // Safe byte/char comparison: '%' (37) is between 0 and 128.
            if (currentByte == '%') {
                outputCurrentByte = handleToken(formatBuffer, wallTime, zoneInfo);
            }
            if (outputCurrentByte) {
                outputByte(formatBuffer.get(formatBuffer.position()));
            }

            formatBuffer.position(formatBuffer.position() + 1);
        }
    }

    private boolean handleToken(ByteBuffer formatBuffer, ZoneInfo.WallTime wallTime,
            ZoneInfo zoneInfo) {

        // The byte at formatBuffer.position() is expected to be '%' at this point.
        int modifier = 0;
        while (formatBuffer.remaining() > 1) {
            // Increment the position then get the new current byte.
            formatBuffer.position(formatBuffer.position() + 1);
            char currentByteAsChar = convertToChar(formatBuffer.get(formatBuffer.position()));
            switch (currentByteAsChar) {
                case 'A':
                    modifyAndAppend((wallTime.getWeekDay() < 0
                                    || wallTime.getWeekDay() >= DAYSPERWEEK)
                                    ? "?" : localeData.longWeekdayNames[wallTime.getWeekDay() + 1],
                            modifier);
                    return false;
                case 'a':
                    modifyAndAppend((wallTime.getWeekDay() < 0
                                    || wallTime.getWeekDay() >= DAYSPERWEEK)
                                    ? "?" : localeData.shortWeekdayNames[wallTime.getWeekDay() + 1],
                            modifier);
                    return false;
                case 'B':
                    if (modifier == '-') {
                        modifyAndAppend((wallTime.getMonth() < 0
                                        || wallTime.getMonth() >= MONSPERYEAR)
                                        ? "?"
                                        : localeData.longStandAloneMonthNames[wallTime.getMonth()],
                                modifier);
                    } else {
                        modifyAndAppend((wallTime.getMonth() < 0
                                        || wallTime.getMonth() >= MONSPERYEAR)
                                        ? "?" : localeData.longMonthNames[wallTime.getMonth()],
                                modifier);
                    }
                    return false;
                case 'b':
                case 'h':
                    modifyAndAppend((wallTime.getMonth() < 0 || wallTime.getMonth() >= MONSPERYEAR)
                                    ? "?" : localeData.shortMonthNames[wallTime.getMonth()],
                            modifier);
                    return false;
                case 'C':
                    outputYear(wallTime.getYear(), true, false, modifier);
                    return false;
                case 'c':
                    formatInternal(dateTimeFormat, wallTime, zoneInfo);
                    return false;
                case 'D':
                    formatInternal("%m/%d/%y", wallTime, zoneInfo);
                    return false;
                case 'd':
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"),
                            wallTime.getMonthDay());
                    return false;
                case 'E':
                case 'O':
                    // C99 locale modifiers are not supported.
                    continue;
                case '_':
                case '-':
                case '0':
                case '^':
                case '#':
                    modifier = currentByteAsChar;
                    continue;
                case 'e':
                    outputFormattedInt(getFormat(modifier, "%2d", "%2d", "%d", "%02d"),
                            wallTime.getMonthDay());
                    return false;
                case 'F':
                    formatInternal("%Y-%m-%d", wallTime, zoneInfo);
                    return false;
                case 'H':
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"),
                            wallTime.getHour());
                    return false;
                case 'I':
                    int hour = (wallTime.getHour() % 12 != 0) ? (wallTime.getHour() % 12) : 12;
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"), hour);
                    return false;
                case 'j':
                    int yearDay = wallTime.getYearDay() + 1;
                    outputFormattedInt(getFormat(modifier, "%03d", "%3d", "%d", "%03d"),
                            yearDay);
                    return false;
                case 'k':
                    outputFormattedInt(getFormat(modifier, "%2d", "%2d", "%d", "%02d"),
                            wallTime.getHour());
                    return false;
                case 'l':
                    int n2 = (wallTime.getHour() % 12 != 0) ? (wallTime.getHour() % 12) : 12;
                    outputFormattedInt(getFormat(modifier, "%2d", "%2d", "%d", "%02d"), n2);
                    return false;
                case 'M':
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"),
                            wallTime.getMinute());
                    return false;
                case 'm':
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"),
                            wallTime.getMonth() + 1);
                    return false;
                case 'n':
                    modifyAndAppend("\n", modifier);
                    return false;
                case 'p':
                    modifyAndAppend((wallTime.getHour() >= (HOURSPERDAY / 2)) ? localeData.amPm[1]
                            : localeData.amPm[0], modifier);
                    return false;
                case 'P':
                    modifyAndAppend((wallTime.getHour() >= (HOURSPERDAY / 2)) ? localeData.amPm[1]
                            : localeData.amPm[0], FORCE_LOWER_CASE);
                    return false;
                case 'R':
                    formatInternal("%H:%M", wallTime, zoneInfo);
                    return false;
                case 'r':
                    formatInternal("%I:%M:%S %p", wallTime, zoneInfo);
                    return false;
                case 'S':
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"),
                            wallTime.getSecond());
                    return false;
                case 's':
                    int timeInSeconds = wallTime.mktime(zoneInfo);
                    modifyAndAppend(Integer.toString(timeInSeconds), modifier);
                    return false;
                case 'T':
                    formatInternal("%H:%M:%S", wallTime, zoneInfo);
                    return false;
                case 't':
                    modifyAndAppend("\t", modifier);
                    return false;
                case 'U':
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"),
                            (wallTime.getYearDay() + DAYSPERWEEK - wallTime.getWeekDay())
                                    / DAYSPERWEEK);
                    return false;
                case 'u':
                    int day = (wallTime.getWeekDay() == 0) ? DAYSPERWEEK : wallTime.getWeekDay();
                    outputFormattedInt("%d", day);
                    return false;
                case 'V':   /* ISO 8601 week number */
                case 'G':   /* ISO 8601 year (four digits) */
                case 'g':   /* ISO 8601 year (two digits) */
                {
                    int year = wallTime.getYear();
                    int yday = wallTime.getYearDay();
                    int wday = wallTime.getWeekDay();
                    int w;
                    while (true) {
                        int len = isLeap(year) ? DAYSPERLYEAR : DAYSPERNYEAR;
                        // What yday (-3 ... 3) does the ISO year begin on?
                        int bot = ((yday + 11 - wday) % DAYSPERWEEK) - 3;
                        // What yday does the NEXT ISO year begin on?
                        int top = bot - (len % DAYSPERWEEK);
                        if (top < -3) {
                            top += DAYSPERWEEK;
                        }
                        top += len;
                        if (yday >= top) {
                            ++year;
                            w = 1;
                            break;
                        }
                        if (yday >= bot) {
                            w = 1 + ((yday - bot) / DAYSPERWEEK);
                            break;
                        }
                        --year;
                        yday += isLeap(year) ? DAYSPERLYEAR : DAYSPERNYEAR;
                    }
                    if (currentByteAsChar == 'V') {
                        outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"), w);
                    } else if (currentByteAsChar == 'g') {
                        outputYear(year, false, true, modifier);
                    } else {
                        outputYear(year, true, true, modifier);
                    }
                    return false;
                }
                case 'v':
                    formatInternal("%e-%b-%Y", wallTime, zoneInfo);
                    return false;
                case 'W':
                    int n = (wallTime.getYearDay() + DAYSPERWEEK - (
                                    wallTime.getWeekDay() != 0 ? (wallTime.getWeekDay() - 1)
                                            : (DAYSPERWEEK - 1))) / DAYSPERWEEK;
                    outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"), n);
                    return false;
                case 'w':
                    outputFormattedInt("%d", wallTime.getWeekDay());
                    return false;
                case 'X':
                    formatInternal(timeOnlyFormat, wallTime, zoneInfo);
                    return false;
                case 'x':
                    formatInternal(dateOnlyFormat, wallTime, zoneInfo);
                    return false;
                case 'y':
                    outputYear(wallTime.getYear(), false, true, modifier);
                    return false;
                case 'Y':
                    outputYear(wallTime.getYear(), true, true, modifier);
                    return false;
                case 'Z':
                    if (wallTime.getIsDst() < 0) {
                        return false;
                    }
                    boolean isDst = wallTime.getIsDst() != 0;
                    modifyAndAppend(zoneInfo.getDisplayName(isDst, TimeZone.SHORT), modifier);
                    return false;
                case 'z': {
                    if (wallTime.getIsDst() < 0) {
                        return false;
                    }
                    int diff = wallTime.getGmtOffset();
                    String sign;
                    if (diff < 0) {
                        sign = "-";
                        diff = -diff;
                    } else {
                        sign = "+";
                    }
                    modifyAndAppend(sign, modifier);
                    diff /= SECSPERMIN;
                    diff = (diff / MINSPERHOUR) * 100 + (diff % MINSPERHOUR);
                    outputFormattedInt(getFormat(modifier, "%04d", "%4d", "%d", "%04d"), diff);
                    return false;
                }
                case '+':
                    formatInternal("%a %b %e %H:%M:%S %Z %Y", wallTime, zoneInfo);
                    return false;
                case '%':
                    // If conversion char is undefined, behavior is undefined. Print out the
                    // character itself.
                default:
                    return true;
            }
        }
        return true;
    }

    private void modifyAndAppend(String str, int modifier) {
        byte[] bytes = str.getBytes(StandardCharsets.UTF_8);
        switch (modifier) {
            case FORCE_LOWER_CASE:
                for (byte b : bytes) {
                    outputByte(brokenToLower(b));
                }
                break;
            case '^':
                for (byte b : bytes) {
                    outputByte(brokenToUpper(b));
                }
                break;
            case '#':
                for (byte b : bytes) {
                    if (brokenIsUpper(b)) {
                        b = brokenToLower(b);
                    } else if (brokenIsLower(b)) {
                        b = brokenToUpper(b);
                    }
                    outputByte(b);
                }
                break;
            default:
                for (byte aByte : bytes) {
                    outputByte(aByte);
                }
        }
    }

    private void outputYear(int value, boolean outputTop, boolean outputBottom, int modifier) {
        int lead;
        int trail;

        final int DIVISOR = 100;
        trail = value % DIVISOR;
        lead = value / DIVISOR + trail / DIVISOR;
        trail %= DIVISOR;
        if (trail < 0 && lead > 0) {
            trail += DIVISOR;
            --lead;
        } else if (lead < 0 && trail > 0) {
            trail -= DIVISOR;
            ++lead;
        }
        if (outputTop) {
            if (lead == 0 && trail < 0) {
                modifyAndAppend("-0", modifier);
            } else {
                outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"), lead);
            }
        }
        if (outputBottom) {
            int n = ((trail < 0) ? -trail : trail);
            outputFormattedInt(getFormat(modifier, "%02d", "%2d", "%d", "%02d"), n);
        }
    }

    private static String getFormat(int modifier, String normal, String underscore, String dash,
            String zero) {
        switch (modifier) {
            case '_':
                return underscore;
            case '-':
                return dash;
            case '0':
                return zero;
        }
        return normal;
    }

    /**
     * Output the bytes for a formatted int.
     */
    private void outputFormattedInt(String format, int value) {
        formatter.format(format, value);
        formatter.flush();
    }

    /**
     * Output a single byte.
     */
    private void outputByte(byte b) {
        try {
            emittedBytesStream.write(b);
        } catch (IOException e) {
            throw new AssertionError(e);
        }
    }

    private static boolean isLeap(int year) {
        return (((year) % 4) == 0 && (((year) % 100) != 0 || ((year) % 400) == 0));
    }

    /**
     * A byte-based implementation of {@link Character#isUpperCase(char)} that assumes ASCII in
     * order to be compatible with the old native implementation.
     */
    private static boolean brokenIsUpper(byte toCheck) {
        // Mixing byte and char is safe here because the char literals are in the range 0-127.
        return toCheck >= 'A' && toCheck <= 'Z';
    }

    /**
     * A byte-based implementation of {@link Character#isLowerCase(char)} that assumes ASCII in
     * order to be compatible with the old native implementation.
     */
    private static boolean brokenIsLower(byte toCheck) {
        // Mixing byte and char is safe here because the char literals are in the range 0-127.
        return toCheck >= 'a' && toCheck <= 'z';
    }

    /**
     * A byte-based implementation of {@link Character#toLowerCase(char)} that assumes ASCII in
     * order to be compatible with the old native implementation.
     */
    private static byte brokenToLower(byte input) {
        // Mixing byte and char is safe here because the char literals are in the range 0-127.
        if (input >= 'A' && input <= 'Z') {
            return (byte) (input - 'A' + 'a');
        }
        return input;
    }

    /**
     * A byte-based  implementation of {@link Character#toUpperCase(char)} that assumes ASCII in
     * order to be compatible with the old native implementation.
     */
    private static byte brokenToUpper(byte input) {
        // Mixing byte and char is safe here because the char literals are in the range 0-127.
        if (input >= 'a' && input <= 'z') {
            return (byte) (input - 'a' + 'A');
        }
        return input;
    }

    /**
     * Safely convert a byte containing an ASCII character to a char, even for character codes
     * > 127.
     */
    private static char convertToChar(byte b) {
        return (char) (b & 0xFF);
    }
}
